namespace :version do

  desc "Updates the application version file - #{Rails.root}/config/app_version.yml\n" +
       "Usage: rake version:tag VERSION=1.0.0"
  task :tag do
    ver = ENV['VERSION']
    if ver.nil?
      fail "You must specify a version (using VERSION=x.y.z) in order to use this task."
    end

    (major,minor,revision) = ver.split(/_|\./)
    app_version_file_path = "#{Rails.root}/config/app_version.yml"

    File.open(app_version_file_path, "w+") do |version_file|
      version_file.puts "# This file is automatically generated by the Tag rake task. rake version:tag VERSION=#{ver}\n"
      version_file.puts "major: #{major}\n"
      version_file.puts "minor: #{minor}\n"
      version_file.puts "revision: #{revision}\n"
      version_file.puts "time: #{Time.now}\n"
    end

    tag_name = "v#{ver}"
    system("git commit '#{app_version_file_path}' -m 'Version #{ver}.'")
    system("git tag -a '#{tag_name}' -m 'Version #{ver}.'")

    puts "Version updated to #{ver} and tag created. Check the repo, then:"
    puts "  - If everthing's fine, push everything with `git push` and `git push --tags`."
    puts "  - If you want to try again, delete the tag with `git tag -d '#{tag_name}'`\n" +
         "    and roll back the version change with\n" +
         "    `git reset HEAD^ && git checkout #{app_version_file_path}`."
  end

end
