require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe StaffController do
  before(:each) do
    login_as("superuser")
  end
  
  def mock_staff(stubs={})
    # @mock_staff = FactoryGirl.create(:staff)
  end

  describe "GET index" do
    it "assigns all staff as @staff" do
      mock_staff1 = FactoryGirl.create(:staff)
      Staff.stub(:all) { [mock_staff1] }
      get :index
      assigns(:staff).should eq([mock_staff1])
    end
  end

  describe "GET show" do
    it "assigns the requested staff as @staff" do
      Staff.stub(:find).with("37") { mock_staff }
      get :show, :id => "37"
      assigns(:staff).should be(mock_staff)
    end
  end

  describe "GET new" do
    it "assigns a new staff as @staff" do
      Staff.stub(:new) { mock_staff }
      get :new
      assigns(:staff).should be(mock_staff)
    end
  end

  describe "GET edit" do
    it "assigns the requested staff as @staff" do
      Staff.stub(:find).with("37") { mock_staff }
      get :edit, :id => "37"
      assigns(:staff).should be(mock_staff)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created staff as @staff" do
        Staff.stub(:new).with({'these' => 'params'}) { mock_staff(:save => true) }
        post :create, :staff => {'these' => 'params'}
        assigns(:staff).should be(mock_staff)
      end

      it "redirects to the created staff" do
        Staff.stub(:new) { mock_staff(:save => true) }
        post :create, :staff => {}
        response.should redirect_to(staff_url(mock_staff))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved staff as @staff" do
        Staff.stub(:new).with({'these' => 'params'}) { mock_staff(:save => false) }
        post :create, :staff => {'these' => 'params'}
        assigns(:staff).should be(mock_staff)
      end

      it "re-renders the 'new' template" do
        Staff.stub(:new) { mock_staff(:save => false) }
        post :create, :staff => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested staff" do
        Staff.stub(:find).with("37") { mock_staff }
        mock_staff.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :staff => {'these' => 'params'}
      end

      it "assigns the requested staff as @staff" do
        Staff.stub(:find) { mock_staff(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:staff).should be(mock_staff)
      end

      it "redirects to the staff" do
        Staff.stub(:find) { mock_staff(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(staff_url(mock_staff))
      end
    end

    describe "with invalid params" do
      it "assigns the staff as @staff" do
        Staff.stub(:find) { mock_staff(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:staff).should be(mock_staff)
      end

      it "re-renders the 'edit' template" do
        Staff.stub(:find) { mock_staff(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested staff" do
      Staff.stub(:find).with("37") { mock_staff }
      mock_staff.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the staff list" do
      Staff.stub(:find) { mock_staff }
      delete :destroy, :id => "1"
      response.should redirect_to(staff_index_url)
    end
  end

end
