require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe StaffLanguagesController do

  def mock_staff_language(stubs={})
    @mock_staff_language ||= mock_model(StaffLanguage, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all staff_languages as @staff_languages" do
      StaffLanguage.stub(:all) { [mock_staff_language] }
      get :index
      assigns(:staff_languages).should eq([mock_staff_language])
    end
  end

  describe "GET show" do
    it "assigns the requested staff_language as @staff_language" do
      StaffLanguage.stub(:find).with("37") { mock_staff_language }
      get :show, :id => "37"
      assigns(:staff_language).should be(mock_staff_language)
    end
  end

  describe "GET new" do
    it "assigns a new staff_language as @staff_language" do
      StaffLanguage.stub(:new) { mock_staff_language }
      get :new
      assigns(:staff_language).should be(mock_staff_language)
    end
  end

  describe "GET edit" do
    it "assigns the requested staff_language as @staff_language" do
      StaffLanguage.stub(:find).with("37") { mock_staff_language }
      get :edit, :id => "37"
      assigns(:staff_language).should be(mock_staff_language)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created staff_language as @staff_language" do
        StaffLanguage.stub(:new).with({'these' => 'params'}) { mock_staff_language(:save => true) }
        post :create, :staff_language => {'these' => 'params'}
        assigns(:staff_language).should be(mock_staff_language)
      end

      it "redirects to the created staff_language" do
        StaffLanguage.stub(:new) { mock_staff_language(:save => true) }
        post :create, :staff_language => {}
        response.should redirect_to(staff_language_url(mock_staff_language))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved staff_language as @staff_language" do
        StaffLanguage.stub(:new).with({'these' => 'params'}) { mock_staff_language(:save => false) }
        post :create, :staff_language => {'these' => 'params'}
        assigns(:staff_language).should be(mock_staff_language)
      end

      it "re-renders the 'new' template" do
        StaffLanguage.stub(:new) { mock_staff_language(:save => false) }
        post :create, :staff_language => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested staff_language" do
        StaffLanguage.stub(:find).with("37") { mock_staff_language }
        mock_staff_language.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :staff_language => {'these' => 'params'}
      end

      it "assigns the requested staff_language as @staff_language" do
        StaffLanguage.stub(:find) { mock_staff_language(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:staff_language).should be(mock_staff_language)
      end

      it "redirects to the staff_language" do
        StaffLanguage.stub(:find) { mock_staff_language(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(staff_language_url(mock_staff_language))
      end
    end

    describe "with invalid params" do
      it "assigns the staff_language as @staff_language" do
        StaffLanguage.stub(:find) { mock_staff_language(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:staff_language).should be(mock_staff_language)
      end

      it "re-renders the 'edit' template" do
        StaffLanguage.stub(:find) { mock_staff_language(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested staff_language" do
      StaffLanguage.stub(:find).with("37") { mock_staff_language }
      mock_staff_language.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the staff_languages list" do
      StaffLanguage.stub(:find) { mock_staff_language }
      delete :destroy, :id => "1"
      response.should redirect_to(staff_languages_url)
    end
  end

end
